server:
  port: 8883
spring:
  application:
    name: service-c

eureka:
  instance:
    hostname: eureka-server #eureka服务端的实例名称，
    prefer-ip-address: true
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版服务注册中心
      defaultZone: http://localhost:8761/eureka/ #单