spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/test2?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    enabled: true
    fetch-registry: false
    filter-only-up-instances: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
